# Site wide configuration

title: A Code Blog
locale: en_US
description: Articles to not forget.
logo: site-logo.png
search: true
url: http://localhost:4000
# url: http://kiub.github.io
root: /
# Jekyll configuration

permalink:   /:categories/:title/

# Build settings
markdown:    kramdown

highlighter: pygments

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-sitemap
  - octopress-gist
  - octopress-codefence
  - octopress-render-code
  - octopress-include-tag


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# plugins: Directory for Jekyll plugins
plugins: plugins

# code_dir: Directory for code snippets (for include_code plugin)
code_dir: source/downloads/code

# source: source
destination: _site

# Site owner
owner:
  name: Kiubmen
  avatar: bio-photo.jpg
  email: kiubmen@gmail.com
  disqus-shortname:
  twitter: kiubmen
  facebook: #username
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: kiubmen
    analytics:
    verify: 1U8LgpsemzLn5VZOospl5YxO_BWIowOHVDpA_99ulUQ
    ad-client:
    ad-slot:
  bing-verify:
